/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2018-2019 Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This file was generated by cantools version 36.2.0 Fri Jun 25 12:06:47 2021.
 */

#include <string.h>

#include "Lunar_CAN_Messages.h"

static inline uint8_t pack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_right_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint16_t unpack_left_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) << shift);
}

static inline uint8_t unpack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) >> shift);
}

static inline uint16_t unpack_right_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) >> shift);
}

int Lunar_CAN_Messages_bb_battery_status_rsp_pack(
    uint8_t *dst_p,
    const struct Lunar_CAN_Messages_bb_battery_status_rsp_t *src_p,
    size_t size)
{
    uint16_t battery_current_a;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->battery_block_state, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->battery_block_state, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->battery_voltage_v, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->battery_voltage_v, 8u, 0xffu);
    battery_current_a = (uint16_t)src_p->battery_current_a;
    dst_p[4] |= pack_left_shift_u16(battery_current_a, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(battery_current_a, 8u, 0xffu);
    dst_p[6] |= pack_left_shift_u16(src_p->battery_soc, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(src_p->battery_soc, 8u, 0xffu);

    return (8);
}

int Lunar_CAN_Messages_bb_battery_status_rsp_unpack(
    struct Lunar_CAN_Messages_bb_battery_status_rsp_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t battery_current_a;

    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->battery_block_state = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->battery_block_state |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->battery_voltage_v = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->battery_voltage_v |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    battery_current_a = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    battery_current_a |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->battery_current_a = (int16_t)battery_current_a;
    dst_p->battery_soc = unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    dst_p->battery_soc |= unpack_left_shift_u16(src_p[7], 8u, 0xffu);

    return (0);
}

uint16_t Lunar_CAN_Messages_bb_battery_status_rsp_battery_block_state_encode(double value)
{
    return (uint16_t)(value);
}

double Lunar_CAN_Messages_bb_battery_status_rsp_battery_block_state_decode(uint16_t value)
{
    return ((double)value);
}

bool Lunar_CAN_Messages_bb_battery_status_rsp_battery_block_state_is_in_range(uint16_t value)
{
    return (value <= 255u);
}

uint16_t Lunar_CAN_Messages_bb_battery_status_rsp_battery_voltage_v_encode(double value)
{
    return (uint16_t)(value / 0.001);
}

double Lunar_CAN_Messages_bb_battery_status_rsp_battery_voltage_v_decode(uint16_t value)
{
    return ((double)value * 0.001);
}

bool Lunar_CAN_Messages_bb_battery_status_rsp_battery_voltage_v_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int16_t Lunar_CAN_Messages_bb_battery_status_rsp_battery_current_a_encode(double value)
{
    return (int16_t)(value / 0.005);
}

double Lunar_CAN_Messages_bb_battery_status_rsp_battery_current_a_decode(int16_t value)
{
    return ((double)value * 0.005);
}

bool Lunar_CAN_Messages_bb_battery_status_rsp_battery_current_a_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

uint16_t Lunar_CAN_Messages_bb_battery_status_rsp_battery_soc_encode(double value)
{
    return (uint16_t)(value / 0.1);
}

double Lunar_CAN_Messages_bb_battery_status_rsp_battery_soc_decode(uint16_t value)
{
    return ((double)value * 0.1);
}

bool Lunar_CAN_Messages_bb_battery_status_rsp_battery_soc_is_in_range(uint16_t value)
{
    return (value <= 1023u);
}

int Lunar_CAN_Messages_bb_dcdc_status_rsp_pack(
    uint8_t *dst_p,
    const struct Lunar_CAN_Messages_bb_dcdc_status_rsp_t *src_p,
    size_t size)
{
    uint16_t dc_bus_current_a;

    if (size < 4u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 4);

    dst_p[0] |= pack_left_shift_u16(src_p->dc_bus_voltage_v, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->dc_bus_voltage_v, 8u, 0xffu);
    dc_bus_current_a = (uint16_t)src_p->dc_bus_current_a;
    dst_p[2] |= pack_left_shift_u16(dc_bus_current_a, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(dc_bus_current_a, 8u, 0xffu);

    return (4);
}

int Lunar_CAN_Messages_bb_dcdc_status_rsp_unpack(
    struct Lunar_CAN_Messages_bb_dcdc_status_rsp_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t dc_bus_current_a;

    if (size < 4u) {
        return (-EINVAL);
    }

    dst_p->dc_bus_voltage_v = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->dc_bus_voltage_v |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dc_bus_current_a = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dc_bus_current_a |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->dc_bus_current_a = (int16_t)dc_bus_current_a;

    return (0);
}

uint16_t Lunar_CAN_Messages_bb_dcdc_status_rsp_dc_bus_voltage_v_encode(double value)
{
    return (uint16_t)(value / 0.01);
}

double Lunar_CAN_Messages_bb_dcdc_status_rsp_dc_bus_voltage_v_decode(uint16_t value)
{
    return ((double)value * 0.01);
}

bool Lunar_CAN_Messages_bb_dcdc_status_rsp_dc_bus_voltage_v_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int16_t Lunar_CAN_Messages_bb_dcdc_status_rsp_dc_bus_current_a_encode(double value)
{
    return (int16_t)(value / 0.005);
}

double Lunar_CAN_Messages_bb_dcdc_status_rsp_dc_bus_current_a_decode(int16_t value)
{
    return ((double)value * 0.005);
}

bool Lunar_CAN_Messages_bb_dcdc_status_rsp_dc_bus_current_a_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int Lunar_CAN_Messages_bb_cell_voltage1to4_rsp_pack(
    uint8_t *dst_p,
    const struct Lunar_CAN_Messages_bb_cell_voltage1to4_rsp_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->cell1_v, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->cell1_v, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->cell2_v, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->cell2_v, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u16(src_p->cell3_v, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(src_p->cell3_v, 8u, 0xffu);
    dst_p[6] |= pack_left_shift_u16(src_p->cell4_v, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(src_p->cell4_v, 8u, 0xffu);

    return (8);
}

int Lunar_CAN_Messages_bb_cell_voltage1to4_rsp_unpack(
    struct Lunar_CAN_Messages_bb_cell_voltage1to4_rsp_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->cell1_v = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->cell1_v |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->cell2_v = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->cell2_v |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->cell3_v = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    dst_p->cell3_v |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->cell4_v = unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    dst_p->cell4_v |= unpack_left_shift_u16(src_p[7], 8u, 0xffu);

    return (0);
}

uint16_t Lunar_CAN_Messages_bb_cell_voltage1to4_rsp_cell1_v_encode(double value)
{
    return (uint16_t)(value / 0.001);
}

double Lunar_CAN_Messages_bb_cell_voltage1to4_rsp_cell1_v_decode(uint16_t value)
{
    return ((double)value * 0.001);
}

bool Lunar_CAN_Messages_bb_cell_voltage1to4_rsp_cell1_v_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t Lunar_CAN_Messages_bb_cell_voltage1to4_rsp_cell2_v_encode(double value)
{
    return (uint16_t)(value / 0.001);
}

double Lunar_CAN_Messages_bb_cell_voltage1to4_rsp_cell2_v_decode(uint16_t value)
{
    return ((double)value * 0.001);
}

bool Lunar_CAN_Messages_bb_cell_voltage1to4_rsp_cell2_v_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t Lunar_CAN_Messages_bb_cell_voltage1to4_rsp_cell3_v_encode(double value)
{
    return (uint16_t)(value / 0.001);
}

double Lunar_CAN_Messages_bb_cell_voltage1to4_rsp_cell3_v_decode(uint16_t value)
{
    return ((double)value * 0.001);
}

bool Lunar_CAN_Messages_bb_cell_voltage1to4_rsp_cell3_v_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t Lunar_CAN_Messages_bb_cell_voltage1to4_rsp_cell4_v_encode(double value)
{
    return (uint16_t)(value / 0.001);
}

double Lunar_CAN_Messages_bb_cell_voltage1to4_rsp_cell4_v_decode(uint16_t value)
{
    return ((double)value * 0.001);
}

bool Lunar_CAN_Messages_bb_cell_voltage1to4_rsp_cell4_v_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int Lunar_CAN_Messages_bb_cell_voltage5to8_rsp_pack(
    uint8_t *dst_p,
    const struct Lunar_CAN_Messages_bb_cell_voltage5to8_rsp_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->cell5_v, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->cell5_v, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->cell6_v, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->cell6_v, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u16(src_p->cell7_v, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(src_p->cell7_v, 8u, 0xffu);
    dst_p[6] |= pack_left_shift_u16(src_p->cell8_v, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(src_p->cell8_v, 8u, 0xffu);

    return (8);
}

int Lunar_CAN_Messages_bb_cell_voltage5to8_rsp_unpack(
    struct Lunar_CAN_Messages_bb_cell_voltage5to8_rsp_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->cell5_v = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->cell5_v |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->cell6_v = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->cell6_v |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->cell7_v = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    dst_p->cell7_v |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->cell8_v = unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    dst_p->cell8_v |= unpack_left_shift_u16(src_p[7], 8u, 0xffu);

    return (0);
}

uint16_t Lunar_CAN_Messages_bb_cell_voltage5to8_rsp_cell5_v_encode(double value)
{
    return (uint16_t)(value / 0.001);
}

double Lunar_CAN_Messages_bb_cell_voltage5to8_rsp_cell5_v_decode(uint16_t value)
{
    return ((double)value * 0.001);
}

bool Lunar_CAN_Messages_bb_cell_voltage5to8_rsp_cell5_v_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t Lunar_CAN_Messages_bb_cell_voltage5to8_rsp_cell6_v_encode(double value)
{
    return (uint16_t)(value / 0.001);
}

double Lunar_CAN_Messages_bb_cell_voltage5to8_rsp_cell6_v_decode(uint16_t value)
{
    return ((double)value * 0.001);
}

bool Lunar_CAN_Messages_bb_cell_voltage5to8_rsp_cell6_v_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t Lunar_CAN_Messages_bb_cell_voltage5to8_rsp_cell7_v_encode(double value)
{
    return (uint16_t)(value / 0.001);
}

double Lunar_CAN_Messages_bb_cell_voltage5to8_rsp_cell7_v_decode(uint16_t value)
{
    return ((double)value * 0.001);
}

bool Lunar_CAN_Messages_bb_cell_voltage5to8_rsp_cell7_v_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t Lunar_CAN_Messages_bb_cell_voltage5to8_rsp_cell8_v_encode(double value)
{
    return (uint16_t)(value / 0.001);
}

double Lunar_CAN_Messages_bb_cell_voltage5to8_rsp_cell8_v_decode(uint16_t value)
{
    return ((double)value * 0.001);
}

bool Lunar_CAN_Messages_bb_cell_voltage5to8_rsp_cell8_v_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int Lunar_CAN_Messages_bb_cell_voltage9to12_rsp_pack(
    uint8_t *dst_p,
    const struct Lunar_CAN_Messages_bb_cell_voltage9to12_rsp_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->cell9_v, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->cell9_v, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->cell10_v, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->cell10_v, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u16(src_p->cell11_v, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(src_p->cell11_v, 8u, 0xffu);
    dst_p[6] |= pack_left_shift_u16(src_p->cell12_v, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(src_p->cell12_v, 8u, 0xffu);

    return (8);
}

int Lunar_CAN_Messages_bb_cell_voltage9to12_rsp_unpack(
    struct Lunar_CAN_Messages_bb_cell_voltage9to12_rsp_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->cell9_v = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->cell9_v |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->cell10_v = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->cell10_v |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->cell11_v = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    dst_p->cell11_v |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->cell12_v = unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    dst_p->cell12_v |= unpack_left_shift_u16(src_p[7], 8u, 0xffu);

    return (0);
}

uint16_t Lunar_CAN_Messages_bb_cell_voltage9to12_rsp_cell9_v_encode(double value)
{
    return (uint16_t)(value / 0.001);
}

double Lunar_CAN_Messages_bb_cell_voltage9to12_rsp_cell9_v_decode(uint16_t value)
{
    return ((double)value * 0.001);
}

bool Lunar_CAN_Messages_bb_cell_voltage9to12_rsp_cell9_v_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t Lunar_CAN_Messages_bb_cell_voltage9to12_rsp_cell10_v_encode(double value)
{
    return (uint16_t)(value / 0.001);
}

double Lunar_CAN_Messages_bb_cell_voltage9to12_rsp_cell10_v_decode(uint16_t value)
{
    return ((double)value * 0.001);
}

bool Lunar_CAN_Messages_bb_cell_voltage9to12_rsp_cell10_v_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t Lunar_CAN_Messages_bb_cell_voltage9to12_rsp_cell11_v_encode(double value)
{
    return (uint16_t)(value / 0.001);
}

double Lunar_CAN_Messages_bb_cell_voltage9to12_rsp_cell11_v_decode(uint16_t value)
{
    return ((double)value * 0.001);
}

bool Lunar_CAN_Messages_bb_cell_voltage9to12_rsp_cell11_v_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t Lunar_CAN_Messages_bb_cell_voltage9to12_rsp_cell12_v_encode(double value)
{
    return (uint16_t)(value / 0.001);
}

double Lunar_CAN_Messages_bb_cell_voltage9to12_rsp_cell12_v_decode(uint16_t value)
{
    return ((double)value * 0.001);
}

bool Lunar_CAN_Messages_bb_cell_voltage9to12_rsp_cell12_v_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int Lunar_CAN_Messages_bb_cell_temp_rsp_pack(
    uint8_t *dst_p,
    const struct Lunar_CAN_Messages_bb_cell_temp_rsp_t *src_p,
    size_t size)
{
    if (size < 6u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 6);

    dst_p[0] |= pack_left_shift_u8(src_p->submodule1_c, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->submodule2_c, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->submodule3_c, 0u, 0xffu);
    dst_p[3] |= pack_left_shift_u8(src_p->submodule4_c, 0u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->submodule5_c, 0u, 0xffu);
    dst_p[5] |= pack_left_shift_u8(src_p->submodule6_c, 0u, 0xffu);

    return (6);
}

int Lunar_CAN_Messages_bb_cell_temp_rsp_unpack(
    struct Lunar_CAN_Messages_bb_cell_temp_rsp_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 6u) {
        return (-EINVAL);
    }

    dst_p->submodule1_c = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->submodule2_c = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->submodule3_c = unpack_right_shift_u8(src_p[2], 0u, 0xffu);
    dst_p->submodule4_c = unpack_right_shift_u8(src_p[3], 0u, 0xffu);
    dst_p->submodule5_c = unpack_right_shift_u8(src_p[4], 0u, 0xffu);
    dst_p->submodule6_c = unpack_right_shift_u8(src_p[5], 0u, 0xffu);

    return (0);
}

uint8_t Lunar_CAN_Messages_bb_cell_temp_rsp_submodule1_c_encode(double value)
{
    return (uint8_t)((value - -40.0) / 0.5);
}

double Lunar_CAN_Messages_bb_cell_temp_rsp_submodule1_c_decode(uint8_t value)
{
    return (((double)value * 0.5) + -40.0);
}

bool Lunar_CAN_Messages_bb_cell_temp_rsp_submodule1_c_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t Lunar_CAN_Messages_bb_cell_temp_rsp_submodule2_c_encode(double value)
{
    return (uint8_t)((value - -40.0) / 0.5);
}

double Lunar_CAN_Messages_bb_cell_temp_rsp_submodule2_c_decode(uint8_t value)
{
    return (((double)value * 0.5) + -40.0);
}

bool Lunar_CAN_Messages_bb_cell_temp_rsp_submodule2_c_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t Lunar_CAN_Messages_bb_cell_temp_rsp_submodule3_c_encode(double value)
{
    return (uint8_t)((value - -40.0) / 0.5);
}

double Lunar_CAN_Messages_bb_cell_temp_rsp_submodule3_c_decode(uint8_t value)
{
    return (((double)value * 0.5) + -40.0);
}

bool Lunar_CAN_Messages_bb_cell_temp_rsp_submodule3_c_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t Lunar_CAN_Messages_bb_cell_temp_rsp_submodule4_c_encode(double value)
{
    return (uint8_t)((value - -40.0) / 0.5);
}

double Lunar_CAN_Messages_bb_cell_temp_rsp_submodule4_c_decode(uint8_t value)
{
    return (((double)value * 0.5) + -40.0);
}

bool Lunar_CAN_Messages_bb_cell_temp_rsp_submodule4_c_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t Lunar_CAN_Messages_bb_cell_temp_rsp_submodule5_c_encode(double value)
{
    return (uint8_t)((value - -40.0) / 0.5);
}

double Lunar_CAN_Messages_bb_cell_temp_rsp_submodule5_c_decode(uint8_t value)
{
    return (((double)value * 0.5) + -40.0);
}

bool Lunar_CAN_Messages_bb_cell_temp_rsp_submodule5_c_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t Lunar_CAN_Messages_bb_cell_temp_rsp_submodule6_c_encode(double value)
{
    return (uint8_t)((value - -40.0) / 0.5);
}

double Lunar_CAN_Messages_bb_cell_temp_rsp_submodule6_c_decode(uint8_t value)
{
    return (((double)value * 0.5) + -40.0);
}

bool Lunar_CAN_Messages_bb_cell_temp_rsp_submodule6_c_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int Lunar_CAN_Messages_bb_dcdc_temperatures_rsp_pack(
    uint8_t *dst_p,
    const struct Lunar_CAN_Messages_bb_dcdc_temperatures_rsp_t *src_p,
    size_t size)
{
    if (size < 4u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 4);

    dst_p[0] |= pack_left_shift_u16(src_p->bb_heatsink_c, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->bb_heatsink_c, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->fan_duty_cycle, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->fan_duty_cycle, 8u, 0xffu);

    return (4);
}

int Lunar_CAN_Messages_bb_dcdc_temperatures_rsp_unpack(
    struct Lunar_CAN_Messages_bb_dcdc_temperatures_rsp_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 4u) {
        return (-EINVAL);
    }

    dst_p->bb_heatsink_c = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->bb_heatsink_c |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->fan_duty_cycle = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->fan_duty_cycle |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);

    return (0);
}

uint16_t Lunar_CAN_Messages_bb_dcdc_temperatures_rsp_bb_heatsink_c_encode(double value)
{
    return (uint16_t)(value - -60.0);
}

double Lunar_CAN_Messages_bb_dcdc_temperatures_rsp_bb_heatsink_c_decode(uint16_t value)
{
    return ((double)value + -60.0);
}

bool Lunar_CAN_Messages_bb_dcdc_temperatures_rsp_bb_heatsink_c_is_in_range(uint16_t value)
{
    return (value <= 255u);
}

uint16_t Lunar_CAN_Messages_bb_dcdc_temperatures_rsp_fan_duty_cycle_encode(double value)
{
    return (uint16_t)(value / 0.1);
}

double Lunar_CAN_Messages_bb_dcdc_temperatures_rsp_fan_duty_cycle_decode(uint16_t value)
{
    return ((double)value * 0.1);
}

bool Lunar_CAN_Messages_bb_dcdc_temperatures_rsp_fan_duty_cycle_is_in_range(uint16_t value)
{
    return (value <= 1023u);
}

int Lunar_CAN_Messages_inv_l2_n_status_rsp_pack(
    uint8_t *dst_p,
    const struct Lunar_CAN_Messages_inv_l2_n_status_rsp_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->l1_n_voltage_vrms, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->l1_n_voltage_vrms, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->l2_n_voltage_vrms, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->l2_n_voltage_vrms, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u16(src_p->l1_n_current_arms, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(src_p->l1_n_current_arms, 8u, 0xffu);
    dst_p[6] |= pack_left_shift_u16(src_p->l2_n_current_arms, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(src_p->l2_n_current_arms, 8u, 0xffu);

    return (8);
}

int Lunar_CAN_Messages_inv_l2_n_status_rsp_unpack(
    struct Lunar_CAN_Messages_inv_l2_n_status_rsp_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->l1_n_voltage_vrms = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->l1_n_voltage_vrms |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->l2_n_voltage_vrms = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->l2_n_voltage_vrms |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->l1_n_current_arms = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    dst_p->l1_n_current_arms |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->l2_n_current_arms = unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    dst_p->l2_n_current_arms |= unpack_left_shift_u16(src_p[7], 8u, 0xffu);

    return (0);
}

uint16_t Lunar_CAN_Messages_inv_l2_n_status_rsp_l1_n_voltage_vrms_encode(double value)
{
    return (uint16_t)(value / 0.01);
}

double Lunar_CAN_Messages_inv_l2_n_status_rsp_l1_n_voltage_vrms_decode(uint16_t value)
{
    return ((double)value * 0.01);
}

bool Lunar_CAN_Messages_inv_l2_n_status_rsp_l1_n_voltage_vrms_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t Lunar_CAN_Messages_inv_l2_n_status_rsp_l2_n_voltage_vrms_encode(double value)
{
    return (uint16_t)(value / 0.01);
}

double Lunar_CAN_Messages_inv_l2_n_status_rsp_l2_n_voltage_vrms_decode(uint16_t value)
{
    return ((double)value * 0.01);
}

bool Lunar_CAN_Messages_inv_l2_n_status_rsp_l2_n_voltage_vrms_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t Lunar_CAN_Messages_inv_l2_n_status_rsp_l1_n_current_arms_encode(double value)
{
    return (uint16_t)(value / 0.005);
}

double Lunar_CAN_Messages_inv_l2_n_status_rsp_l1_n_current_arms_decode(uint16_t value)
{
    return ((double)value * 0.005);
}

bool Lunar_CAN_Messages_inv_l2_n_status_rsp_l1_n_current_arms_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t Lunar_CAN_Messages_inv_l2_n_status_rsp_l2_n_current_arms_encode(double value)
{
    return (uint16_t)(value / 0.005);
}

double Lunar_CAN_Messages_inv_l2_n_status_rsp_l2_n_current_arms_decode(uint16_t value)
{
    return ((double)value * 0.005);
}

bool Lunar_CAN_Messages_inv_l2_n_status_rsp_l2_n_current_arms_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int Lunar_CAN_Messages_inv_l2_l_status_rsp_pack(
    uint8_t *dst_p,
    const struct Lunar_CAN_Messages_inv_l2_l_status_rsp_t *src_p,
    size_t size)
{
    if (size < 4u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 4);

    dst_p[0] |= pack_left_shift_u16(src_p->l1_l2_voltage_vrms, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->l1_l2_voltage_vrms, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->l1_l2_current_arms, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->l1_l2_current_arms, 8u, 0xffu);

    return (4);
}

int Lunar_CAN_Messages_inv_l2_l_status_rsp_unpack(
    struct Lunar_CAN_Messages_inv_l2_l_status_rsp_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 4u) {
        return (-EINVAL);
    }

    dst_p->l1_l2_voltage_vrms = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->l1_l2_voltage_vrms |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->l1_l2_current_arms = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->l1_l2_current_arms |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);

    return (0);
}

uint16_t Lunar_CAN_Messages_inv_l2_l_status_rsp_l1_l2_voltage_vrms_encode(double value)
{
    return (uint16_t)(value / 0.01);
}

double Lunar_CAN_Messages_inv_l2_l_status_rsp_l1_l2_voltage_vrms_decode(uint16_t value)
{
    return ((double)value * 0.01);
}

bool Lunar_CAN_Messages_inv_l2_l_status_rsp_l1_l2_voltage_vrms_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t Lunar_CAN_Messages_inv_l2_l_status_rsp_l1_l2_current_arms_encode(double value)
{
    return (uint16_t)(value / 0.005);
}

double Lunar_CAN_Messages_inv_l2_l_status_rsp_l1_l2_current_arms_decode(uint16_t value)
{
    return ((double)value * 0.005);
}

bool Lunar_CAN_Messages_inv_l2_l_status_rsp_l1_l2_current_arms_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int Lunar_CAN_Messages_inv_dc_bus_status_rsp_pack(
    uint8_t *dst_p,
    const struct Lunar_CAN_Messages_inv_dc_bus_status_rsp_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->pos_bus_voltage, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->pos_bus_voltage, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->neg_bus_voltage, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->neg_bus_voltage, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u16(src_p->pos_bus_current, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(src_p->pos_bus_current, 8u, 0xffu);
    dst_p[6] |= pack_left_shift_u16(src_p->neg_bus_current, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(src_p->neg_bus_current, 8u, 0xffu);

    return (8);
}

int Lunar_CAN_Messages_inv_dc_bus_status_rsp_unpack(
    struct Lunar_CAN_Messages_inv_dc_bus_status_rsp_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->pos_bus_voltage = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->pos_bus_voltage |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->neg_bus_voltage = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->neg_bus_voltage |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->pos_bus_current = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    dst_p->pos_bus_current |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->neg_bus_current = unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    dst_p->neg_bus_current |= unpack_left_shift_u16(src_p[7], 8u, 0xffu);

    return (0);
}

uint16_t Lunar_CAN_Messages_inv_dc_bus_status_rsp_pos_bus_voltage_encode(double value)
{
    return (uint16_t)(value / 0.01);
}

double Lunar_CAN_Messages_inv_dc_bus_status_rsp_pos_bus_voltage_decode(uint16_t value)
{
    return ((double)value * 0.01);
}

bool Lunar_CAN_Messages_inv_dc_bus_status_rsp_pos_bus_voltage_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t Lunar_CAN_Messages_inv_dc_bus_status_rsp_neg_bus_voltage_encode(double value)
{
    return (uint16_t)(value / 0.01);
}

double Lunar_CAN_Messages_inv_dc_bus_status_rsp_neg_bus_voltage_decode(uint16_t value)
{
    return ((double)value * 0.01);
}

bool Lunar_CAN_Messages_inv_dc_bus_status_rsp_neg_bus_voltage_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t Lunar_CAN_Messages_inv_dc_bus_status_rsp_pos_bus_current_encode(double value)
{
    return (uint16_t)(value / 0.005);
}

double Lunar_CAN_Messages_inv_dc_bus_status_rsp_pos_bus_current_decode(uint16_t value)
{
    return ((double)value * 0.005);
}

bool Lunar_CAN_Messages_inv_dc_bus_status_rsp_pos_bus_current_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t Lunar_CAN_Messages_inv_dc_bus_status_rsp_neg_bus_current_encode(double value)
{
    return (uint16_t)(value / 0.005);
}

double Lunar_CAN_Messages_inv_dc_bus_status_rsp_neg_bus_current_decode(uint16_t value)
{
    return ((double)value * 0.005);
}

bool Lunar_CAN_Messages_inv_dc_bus_status_rsp_neg_bus_current_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int Lunar_CAN_Messages_inv_temperatures_rsp_pack(
    uint8_t *dst_p,
    const struct Lunar_CAN_Messages_inv_temperatures_rsp_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->inv_heatsink_c, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->inv_power_stage1_c, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->inv_power_stage2_c, 0u, 0xffu);
    dst_p[3] |= pack_left_shift_u8(src_p->inv_power_stage3_c, 0u, 0xffu);
    dst_p[4] |= pack_left_shift_u16(src_p->inv_fan_duty_cycle1, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(src_p->inv_fan_duty_cycle1, 8u, 0xffu);
    dst_p[6] |= pack_left_shift_u16(src_p->inv_fan_duty_cycle2, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(src_p->inv_fan_duty_cycle2, 8u, 0xffu);

    return (8);
}

int Lunar_CAN_Messages_inv_temperatures_rsp_unpack(
    struct Lunar_CAN_Messages_inv_temperatures_rsp_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->inv_heatsink_c = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->inv_power_stage1_c = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->inv_power_stage2_c = unpack_right_shift_u8(src_p[2], 0u, 0xffu);
    dst_p->inv_power_stage3_c = unpack_right_shift_u8(src_p[3], 0u, 0xffu);
    dst_p->inv_fan_duty_cycle1 = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    dst_p->inv_fan_duty_cycle1 |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->inv_fan_duty_cycle2 = unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    dst_p->inv_fan_duty_cycle2 |= unpack_left_shift_u16(src_p[7], 8u, 0xffu);

    return (0);
}

uint8_t Lunar_CAN_Messages_inv_temperatures_rsp_inv_heatsink_c_encode(double value)
{
    return (uint8_t)(value - -60.0);
}

double Lunar_CAN_Messages_inv_temperatures_rsp_inv_heatsink_c_decode(uint8_t value)
{
    return ((double)value + -60.0);
}

bool Lunar_CAN_Messages_inv_temperatures_rsp_inv_heatsink_c_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t Lunar_CAN_Messages_inv_temperatures_rsp_inv_power_stage1_c_encode(double value)
{
    return (uint8_t)(value - -60.0);
}

double Lunar_CAN_Messages_inv_temperatures_rsp_inv_power_stage1_c_decode(uint8_t value)
{
    return ((double)value + -60.0);
}

bool Lunar_CAN_Messages_inv_temperatures_rsp_inv_power_stage1_c_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t Lunar_CAN_Messages_inv_temperatures_rsp_inv_power_stage2_c_encode(double value)
{
    return (uint8_t)(value - -60.0);
}

double Lunar_CAN_Messages_inv_temperatures_rsp_inv_power_stage2_c_decode(uint8_t value)
{
    return ((double)value + -60.0);
}

bool Lunar_CAN_Messages_inv_temperatures_rsp_inv_power_stage2_c_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t Lunar_CAN_Messages_inv_temperatures_rsp_inv_power_stage3_c_encode(double value)
{
    return (uint8_t)(value - -60.0);
}

double Lunar_CAN_Messages_inv_temperatures_rsp_inv_power_stage3_c_decode(uint8_t value)
{
    return ((double)value + -60.0);
}

bool Lunar_CAN_Messages_inv_temperatures_rsp_inv_power_stage3_c_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint16_t Lunar_CAN_Messages_inv_temperatures_rsp_inv_fan_duty_cycle1_encode(double value)
{
    return (uint16_t)(value / 0.1);
}

double Lunar_CAN_Messages_inv_temperatures_rsp_inv_fan_duty_cycle1_decode(uint16_t value)
{
    return ((double)value * 0.1);
}

bool Lunar_CAN_Messages_inv_temperatures_rsp_inv_fan_duty_cycle1_is_in_range(uint16_t value)
{
    return (value <= 1023u);
}

uint16_t Lunar_CAN_Messages_inv_temperatures_rsp_inv_fan_duty_cycle2_encode(double value)
{
    return (uint16_t)(value / 0.1);
}

double Lunar_CAN_Messages_inv_temperatures_rsp_inv_fan_duty_cycle2_decode(uint16_t value)
{
    return ((double)value * 0.1);
}

bool Lunar_CAN_Messages_inv_temperatures_rsp_inv_fan_duty_cycle2_is_in_range(uint16_t value)
{
    return (value <= 1023u);
}

int Lunar_CAN_Messages_inv_state_rsp_pack(
    uint8_t *dst_p,
    const struct Lunar_CAN_Messages_inv_state_rsp_t *src_p,
    size_t size)
{
    if (size < 3u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 3);

    dst_p[0] |= pack_left_shift_u8(src_p->inv_state, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->inv_ac_relay, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->inv_l1_l2_in_phase, 0u, 0xffu);

    return (3);
}

int Lunar_CAN_Messages_inv_state_rsp_unpack(
    struct Lunar_CAN_Messages_inv_state_rsp_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 3u) {
        return (-EINVAL);
    }

    dst_p->inv_state = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->inv_ac_relay = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->inv_l1_l2_in_phase = unpack_right_shift_u8(src_p[2], 0u, 0xffu);

    return (0);
}

uint8_t Lunar_CAN_Messages_inv_state_rsp_inv_state_encode(double value)
{
    return (uint8_t)(value);
}

double Lunar_CAN_Messages_inv_state_rsp_inv_state_decode(uint8_t value)
{
    return ((double)value);
}

bool Lunar_CAN_Messages_inv_state_rsp_inv_state_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t Lunar_CAN_Messages_inv_state_rsp_inv_ac_relay_encode(double value)
{
    return (uint8_t)(value);
}

double Lunar_CAN_Messages_inv_state_rsp_inv_ac_relay_decode(uint8_t value)
{
    return ((double)value);
}

bool Lunar_CAN_Messages_inv_state_rsp_inv_ac_relay_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t Lunar_CAN_Messages_inv_state_rsp_inv_l1_l2_in_phase_encode(double value)
{
    return (uint8_t)(value);
}

double Lunar_CAN_Messages_inv_state_rsp_inv_l1_l2_in_phase_decode(uint8_t value)
{
    return ((double)value);
}

bool Lunar_CAN_Messages_inv_state_rsp_inv_l1_l2_in_phase_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int Lunar_CAN_Messages_bb_command_cmd_pack(
    uint8_t *dst_p,
    const struct Lunar_CAN_Messages_bb_command_cmd_t *src_p,
    size_t size)
{
    if (size < 2u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 2);

    dst_p[0] |= pack_left_shift_u8(src_p->bb_state_req, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->bb_reset_req, 0u, 0xffu);

    return (2);
}

int Lunar_CAN_Messages_bb_command_cmd_unpack(
    struct Lunar_CAN_Messages_bb_command_cmd_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 2u) {
        return (-EINVAL);
    }

    dst_p->bb_state_req = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->bb_reset_req = unpack_right_shift_u8(src_p[1], 0u, 0xffu);

    return (0);
}

uint8_t Lunar_CAN_Messages_bb_command_cmd_bb_state_req_encode(double value)
{
    return (uint8_t)(value);
}

double Lunar_CAN_Messages_bb_command_cmd_bb_state_req_decode(uint8_t value)
{
    return ((double)value);
}

bool Lunar_CAN_Messages_bb_command_cmd_bb_state_req_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t Lunar_CAN_Messages_bb_command_cmd_bb_reset_req_encode(double value)
{
    return (uint8_t)(value);
}

double Lunar_CAN_Messages_bb_command_cmd_bb_reset_req_decode(uint8_t value)
{
    return ((double)value);
}

bool Lunar_CAN_Messages_bb_command_cmd_bb_reset_req_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int Lunar_CAN_Messages_inv_command_cmd_pack(
    uint8_t *dst_p,
    const struct Lunar_CAN_Messages_inv_command_cmd_t *src_p,
    size_t size)
{
    if (size < 4u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 4);

    dst_p[0] |= pack_left_shift_u8(src_p->inv_state_req, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->inv_reset_req, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->inv_rapid_shutdown, 0u, 0xffu);
    dst_p[3] |= pack_left_shift_u8(src_p->inv_l1_l2_in_phase_req, 0u, 0xffu);

    return (4);
}

int Lunar_CAN_Messages_inv_command_cmd_unpack(
    struct Lunar_CAN_Messages_inv_command_cmd_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 4u) {
        return (-EINVAL);
    }

    dst_p->inv_state_req = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->inv_reset_req = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->inv_rapid_shutdown = unpack_right_shift_u8(src_p[2], 0u, 0xffu);
    dst_p->inv_l1_l2_in_phase_req = unpack_right_shift_u8(src_p[3], 0u, 0xffu);

    return (0);
}

uint8_t Lunar_CAN_Messages_inv_command_cmd_inv_state_req_encode(double value)
{
    return (uint8_t)(value);
}

double Lunar_CAN_Messages_inv_command_cmd_inv_state_req_decode(uint8_t value)
{
    return ((double)value);
}

bool Lunar_CAN_Messages_inv_command_cmd_inv_state_req_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t Lunar_CAN_Messages_inv_command_cmd_inv_reset_req_encode(double value)
{
    return (uint8_t)(value);
}

double Lunar_CAN_Messages_inv_command_cmd_inv_reset_req_decode(uint8_t value)
{
    return ((double)value);
}

bool Lunar_CAN_Messages_inv_command_cmd_inv_reset_req_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t Lunar_CAN_Messages_inv_command_cmd_inv_rapid_shutdown_encode(double value)
{
    return (uint8_t)(value);
}

double Lunar_CAN_Messages_inv_command_cmd_inv_rapid_shutdown_decode(uint8_t value)
{
    return ((double)value);
}

bool Lunar_CAN_Messages_inv_command_cmd_inv_rapid_shutdown_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t Lunar_CAN_Messages_inv_command_cmd_inv_l1_l2_in_phase_req_encode(double value)
{
    return (uint8_t)(value);
}

double Lunar_CAN_Messages_inv_command_cmd_inv_l1_l2_in_phase_req_decode(uint8_t value)
{
    return ((double)value);
}

bool Lunar_CAN_Messages_inv_command_cmd_inv_l1_l2_in_phase_req_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}
